"""Revise Profile Photo of Provider Model to Portfolio Photo

Revision ID: 458c313ffb8a
Revises: e406f801245f
Create Date: 2025-07-23 12:05:09.922468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '458c313ffb8a'
down_revision: Union[str, Sequence[str], None] = 'e406f801245f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_profiles', sa.Column('portfolio_photo', sa.JSON(), nullable=True))
    op.drop_column('provider_profiles', 'profile_photo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_profiles', sa.Column('profile_photo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('provider_profiles', 'portfolio_photo')
    # ### end Alembic commands ###
