"""Added Profile Photo to User Model

Revision ID: 4702e61c3d0d
Revises: edf4e98cdab3
Create Date: 2025-07-23 11:49:12.610785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4702e61c3d0d'
down_revision: Union[str, Sequence[str], None] = 'edf4e98cdab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_photo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_photo')
    # ### end Alembic commands ###
