"""Revise Profile Photo of Provider Model to Portfolio Photo

Revision ID: e406f801245f
Revises: 4702e61c3d0d
Create Date: 2025-07-23 11:59:23.900346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e406f801245f'
down_revision: Union[str, Sequence[str], None] = '4702e61c3d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
